### ISSUE TITLE
Editing of Regions in SC

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#276]
In South Carolina, when a school is entered, we have to identify a district and region for the school. They have decided to change the names of the districts from:

Pidemont Region to Region 1
Mid-State Region to Region 2
Pee Dee Region to Region 3
Lower State Region to Region 4

What is your estimate of time involved to make these changes?

**Comment by bguerrettaz** [comment]
Just an hour for these changes.

**Comment by dpentony** [comment]
Please proceed

**Comment by bguerrettaz** [comment]
This is complete.  Please confirm.

Thanks,
Blake

**Comment by dpentony** [comment]
I am unable to check this. On the Admin site, when I go to Edit/Delete School and pull up the list of SC schools, if I click on Edit for any school, I get the following error message:

ADODB.Field error '800a0bcd'

Either BOF or EOF is True, or the current record has been deleted. Requested operation requires a current record.

/admin/School/EditSchool.asp, line 46

**Comment by bguerrettaz** [comment]
There was another reference to the old districts, I've corrected.  Please
try again.

**Comment by dpentony** [comment]
I see two issues:

1. When you go to change the School District from Region 1 to Region 2 as I tried to do for Abbeville HS, I get this error message:

ADODB.Field error '800a0bcd'

Either BOF or EOF is True, or the current record has been deleted. Requested operation requires a current record.

/admin/School/UpdateSchool.asp, line 98

2. Can you make the School Section line disappear as it no longer applies.

**Comment by bguerrettaz** [comment]
For number two, are you wanting school section removed for all schools and
all states or just SC?  There's more code involved to do it just for SC.

Working on number one, but its tied to the section detail that doesn't
change with the district like it used to.

**Comment by dpentony** [comment]
Disregard #2.

**Comment by bguerrettaz** [comment]
As far as number 1, it seems as if you have to change to the appropriate
section once you change the district.  That's how it's currently designed,
I checked other states to make sure that was the case.

So if you want to change the district on any school, you have to change the
corresponding section or else you'll get an error because the new
combination doesn't return anything from the database (new district + old
section = doesn't match)

It should be working per normal now following that.

**Comment by dpentony** [comment]
I can't check it. I get this error message when I click to Edit a school:

SELECT State, RegionID, SectionID, Region, [Section] FROM tblStateFilter WHERE (State = 'SC') AND (Region = 'Piedmont') AND (Section = 'Piedmont')
ADODB.Field error '800a0bcd'

Either BOF or EOF is True, or the current record has been deleted. Requested operation requires a current record.

/admin/School/EditSchool.asp, line 49

**Comment by bguerrettaz** [comment]
Please try again.

**Comment by dpentony** [comment]
Still getting an error message. I tried to change Abbeville HS from Region 1 to Region 2. When I click on Save School Changes, I get this error message:

DODB.Field error '800a0bcd'

Either BOF or EOF is True, or the current record has been deleted. Requested operation requires a current record.

/admin/School/UpdateSchool.asp, line 98

**Comment by dpentony** [comment]
I understand now. Looks good. Thanks.

**Comment by dpentony** [comment]
@bguerrettaz - can you revert the changes you made for the regions in SC? They really messed things up on the state admin page. I thought the changes would be a simple thing but it is not proving to be so. 

If you go to the admin site and choose SC from the pull down, you can get to the SC admin page. Go to Maintain Teachers>>Edit Teacher, and choose any region, the only teachers listed are at those schools I edited today after you made the final changes. I edited them because they had changed regions. However, all other schools that used to be in the same regions did not show up.

This has opened a can of worms. We were doing this as a favor to SC. I think it would be best to revert the changes back to the way things used to be. Once that is done we'll have to see if we can add a teacher via the state admin page. I tried earlier and it gave me an error message.

**Comment by bguerrettaz** [comment]
Luckily I generally save off the previous version.  I've reverted back,
please try your test.

Blake

**Comment by dpentony** [comment]
That solved the main problem, but there still seems to be a problem when adding a teacher from the state admin site. Via the state admin site, I added a teacher named Kilbury Darren. It appeared to add it correctly. However, if you go to the global admin and edit that teacher, you get the following screen where the libraries that teacher has access to should appear:

![image](https://user-images.githubusercontent.com/5790325/43978291-5eb8e7e6-9cac-11e8-9315-00c6cef3e46a.png)

**Comment by mnichols13** [comment]
This is still not fixed.. SC admins cannot add teachers...  Please advise ASAP

**Comment by mnichols13** [comment]
![image](https://user-images.githubusercontent.com/5790342/45966371-8b01b000-bff0-11e8-8b0d-65e1172f0a28.png)

**Comment by mnichols13** [comment]
still not working

**Comment by bguerrettaz** [comment]
Please try again.  These state admin pages are a mess, so I'm trying to
clean up.

**Comment by mnichols13** [comment]
looks good, I think all is ok
